### ISSUE TITLE
Requirement python=3.7 necessary?

### ISSUE THREAD

**Issue by julian-belina** [cakemanny/fastclasses-json#8]
Hello,

ist it necessary to fix the python version to 3.7 in the setup.py file?  It also runs with python 3.12 e.g.

**Comment by cakemanny** [comment]
Hi Julian,

Are you running into a specific problem I can help with?

There's nothing restricting the version to python 3.7 that I'm aware of.

This line just states that 3.7 is a minimum:
https://github.com/cakemanny/fastclasses-json/blob/9f6c58bb66fac38742f89a2d57bd0c86eb53aaea/setup.py#L24
and the install requires section adds `typing_extensions` for those using python 3.7, so that we are able to use certain features from the `typing` module that were first brought to the standard library in 3.8.
https://github.com/cakemanny/fastclasses-json/blob/9f6c58bb66fac38742f89a2d57bd0c86eb53aaea/setup.py#L25-L27
